### ISSUE TITLE
Advise for README.md install (mac 10.4 + users using conda (anaconda))

### ISSUE THREAD

**Issue by scotgl** [sonoUnoTeam/sonoUno-desktop#1]
I was able to use the instructions given, but not without some extensive work for my development environment - my notes:
Here is the terminal display error I got originally:
Successfully installed sonoUno-3.1.0
(base) ScotMacBookPro:sonoUno scot$ cd sonoUno/
(base) ScotMacBookPro:sonoUno scot$ sonoUno
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.

I am using conda, (anacondo python) and a virtual environment. So I had to make a new env running python 2.7 so pygame would work ... (took a while to figure that out) so if running conda look here https://uoa-eresearch.github.io/eresearch-cookbook/recipe/2014/11/20/conda/
with that information I did the command:
conda create -n sonoUno27 python=2.7 anaconda
which created the environment sonoUno27 which I then activated with:
source activate sonoUno27
I was then able to follow your instructions for mac and get it to install and run fine in the new sonoUno27 env.

**Comment by johicasado** [comment]
Sorry for not answer earlier to this issue! and thank you very much for all your work!!

I hope you enjoy the software! Do you have any additional problem?
